/*** Base de datos para llevar el control de la correspondencia del Complejo Administrativo de Colima***/

/*** Creada por el estudiante de Ingenieria en sistemas computacionales: Alejandro Garcia Alvarez, como respuesta 
	 a la problematica del sistema de correspondencia actual 2008-2019 del area de la Secretaria de Desarrollo Rural
	 del estado de Colima ***/ 

 /*** Ingeniero a cargo 
		  ISC. Alejandro Dias   ***/

/*** Sistema  de Correspondencia a cargo de los Alumnos del Tecnologico Nacional de Mexico/Tecnologico de Colima
	 de la carrera en Ingenieria en sistemas computacionales  
	 Avalos Barrales Jessy
	 Garcia Alvarez Alejandro 
	 Martinez Verduzco Saharabi Guadalupe
	 ***/

/*** Fecha de Inicio de la creacionde la base de datos 18/02/2019 ***/


/*** CREACION DE LA BASE DE DATOS LLAMADA cORRESPONDENCIA ***/
CREATE DATABASE [CORRESPONDENCIA]

GO 

USE [CORRESPONDENCIA]

GO 

/*** CREAACION DE LAS TABLAS QUE CORRESPONDERAN A LA BASE DE DATOS ***/

CREATE TABLE [TBL_DOCUMENTOS] 
	(
		ID_DOCUMENTO INT IDENTITY  NOT NULL,
		ID_REMITENTE INT NOT NULL,
		ID_DIRECCION INT NOT NULL,
		ID_TIPO_DOC INT NOT NULL,
		ID_CARGA_USUARIO INT NOT NULL,
		FOLIO VARCHAR (9) NOT NULL,
		TURNADO BIT  NOT NULL,
		FECHA_CAPTURA SMALLDATETIME NOT NULL,
		FECHA_ENVIO SMALLDATETIME,
		ESTADO  BIT DEFAULT 0 NOT NULL,
		RESPUESTA VARCHAR (500),
		RESUMEN VARCHAR (500),
		IMAGEN IMAGE, 
		COPIA_FISICA BIT DEFAULT 0	NOT NULL 	 	
	);
	
/*** CREACION DE LOS CATALOGOS ***/
GO
CREATE TABLE [CAT_USUARIO] 
	(
		ID_USUARIO INT IDENTITY  NOT NULL,
		ID_DIRECCION INT NOT NULL,
		TIPO_USUARIO BIT NOT NULL,
		NOMBRE VARCHAR (50) NOT NULL,
		APELLIDO_PATERNO VARCHAR (25) NOT NULL,
		APELLIDO_MATERNO VARCHAR (25) NOT NULL,
		CLAVE VARCHAR (12) NOT NULL,
	);
	GO
CREATE  TABLE [CAT_DIRECCION]
	(
		ID_DIRECCION INT IDENTITY  NOT NULL,
		NOMBRE VARCHAR (60) NOT NULL, 
	);
	GO
CREATE TABLE [CAT_ORIGENES]
	(
		ID_ORIGEN INT IDENTITY  NOT NULL,
		NOMBRE VARCHAR (50) NOT NULL
	);
	GO
CREATE TABLE [CAT_REMITENTES] 
	(
		ID_REMITENTE INT IDENTITY  NOT NULL,
		ID_ORIGEN INT,
		NOMBRE VARCHAR (50) NOT NULL,
		APELLIDO_PATERNO VARCHAR (25) NOT NULL,
		APELLIDO_MATERNO VARCHAR (25) NOT NULL,
		CARGO VARCHAR (30) NOT NULL,
	);
	GO
CREATE TABLE [CAT_TIPO]
	(
		ID_TIPO INT IDENTITY  NOT NULL,
		TIPO VARCHAR (30) NOT NULL
	);

/*** DECLARACION DE LAS LLAVES PRIMARIAS DE LAS TABLAS Y CATALOGOS ***/
GO
ALTER TABLE [TBL_DOCUMENTOS] 
	ADD CONSTRAINT PK_ID_DOCUMENTO PRIMARY KEY (ID_DOCUMENTO);
GO 
ALTER TABLE [CAT_USUARIO]
	ADD CONSTRAINT PK_ID_USUARIO PRIMARY KEY (ID_USUARIO);
GO
ALTER TABLE [CAT_DIRECCION] 
	ADD CONSTRAINT PK_ID_DIRECCION PRIMARY KEY (ID_DIRECCION);
GO 
ALTER TABLE [CAT_ORIGENES] 
	ADD CONSTRAINT PK_ID_ORIGEN PRIMARY KEY (ID_ORIGEN);
GO 
ALTER TABLE [CAT_REMITENTES]
	ADD CONSTRAINT PK_ID_REMITENTE PRIMARY KEY (ID_REMITENTE);
GO 
ALTER TABLE [CAT_TIPO]
	ADD CONSTRAINT PR_ID_TIPO PRIMARY KEY (ID_TIPO);


/*** DECLARACION DE LAS LLAVES FORANEAS DE LAS TABLAS Y CATALOGOS ***/
GO
ALTER TABLE [CAT_REMITENTES]
	ADD CONSTRAINT FK_ID_ORIGEN
	FOREIGN KEY (ID_ORIGEN) REFERENCES [CAT_ORIGENES](ID_ORIGEN);
GO
ALTER TABLE [TBL_DOCUMENTOS]
	ADD CONSTRAINT FK_ID_REMITENTE
	FOREIGN KEY (ID_REMITENTE) REFERENCES [CAT_REMITENTES](ID_REMITENTE);
GO
ALTER TABLE [TBL_DOCUMENTOS]
	ADD CONSTRAINT FK_ID_DESTINATARIO
	FOREIGN KEY (ID_DESTINATARIO) REFERENCES [CAT_USUARIO](ID_USUARIO);
GO
ALTER TABLE [TBL_DOCUMENTOS]
	ADD CONSTRAINT FK_ID_CARGA_USUARIO
	FOREIGN KEY (ID_CARGA_USUARIO) REFERENCES [CAT_USUARIO](ID_USUARIO);
GO
ALTER TABLE [TBL_DOCUMENTOS]
	ADD CONSTRAINT FK_ID_TIPO_DOC
	FOREIGN KEY (ID_TIPO_DOC) REFERENCES [CAT_TIPO](ID_TIPO);
GO
ALTER TABLE [CAT_USUARIO]
	ADD CONSTRAINT FK_ID_DIRECCION
	FOREIGN KEY (ID_DIRECCION) REFERENCES [CAT_DIRECCION](ID_DIRECCION);
GO


/*** MODIFICACIONES RECOMENDADAS POR EL CLIENTE***/
ALTER TABLE CAT_USUARIO ADD CORREO VARCHAR(50);
ALTER TABLE CAT_USUARIO ADD TELEFONO VARCHAR(10);

ALTER TABLE CAT_REMITENTES ADD CORREO VARCHAR(50);
ALTER TABLE CAT_REMITENTES ADD TELEFONO VARCHAR(10);

