  USE CORRESPONDENCIA
  --INSERTAR CAT_dIRECCION
  INSERT INTO CAT_DIRECCION VALUES('SEDER')
  INSERT INTO CAT_DIRECCION VALUES('SAGARPA')
  INSERT INTO CAT_DIRECCION VALUES('SECRETARIA PRINCIPAL')
  --INSERT CAT_USUARIO
  INSERT INTO CAT_USUARIO VALUES (1,'MIGUEL','MARQUEZ','ALVAREZ','ABCD12345','MIGUEL.MARQUEZ@GMAIL.COM','3131458796')
  INSERT INTO CAT_USUARIO VALUES (2,'MARCOS','GUILLEN','FARIAS ','ABCD65412','MARCOS.FARIAS@GMAIL.COM','3121448727')
  INSERT INTO CAT_USUARIO VALUES (1,'DULCE','GALVAN  ','PEREZ  ','ABCD48793','DULCE.GALVAN@GMAIL.COM ','3124856245')
  INSERT INTO CAT_USUARIO VALUES (2,'BRYAN','MENDOZA','GONZALES','ABCD35266','BRYAN.MENDOZA@GMAIL.COM','2542572425')
  INSERT INTO CAT_USUARIO VALUES (3,'DINNORA','LOPEZ','ZALDIVAR','ABCD68335','DINNORA.LOPEZ@GMAIL.COM','3125866863')
  --INSERTAR CAR_TIPO_DOC
  INSERT INTO CAT_TIPO VALUES('INVITACION')
  INSERT INTO CAT_TIPO VALUES('SOLICITUD')
  INSERT INTO CAT_TIPO VALUES('INFORME')