USE CORRESPONDENCIA
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,ALEJANDRO GARCIA ALVAREAZ>
-- Create date: <Create Date, 29-09-2019>
-- Description:	<Description, DARA DE ALTA A LOS REMITENTES Y AL CATALOGO DE ORIGENES>
-- =============================================
CREATE PROCEDURE sp_InsertRemitentesOrigen
	-- Add the parameters for the stored procedure here
--PARAMETROS PARA TABLA CAT_REMITENTES
@NOMBRE VARCHAR (50),
@APELLIDOP VARCHAR (25),
@APELLIDOM VARCHAR (25),
@CARGO VARCHAR(30),
@CORRE0 VARCHAR(50),
@TELEFONO VARCHAR(10),
--PARAMETROS PARA TABLA CAT_ORIGENES
@NOMBREO VARCHAR(50)

--ID RECUPERACION 

AS
BEGIN
DECLARE @ID_ORIGEN INT;

IF EXISTS (SELECT 1 FROM CAT_ORIGENES WHERE NOMBRE=@NOMBREO) 
BEGIN


	SELECT @ID_ORIGEN=ID_ORIGEN 
		FROM CAT_ORIGENES 
			WHERE NOMBRE=@NOMBREO
END
ELSE
BEGIN
	INSERT INTO CAT_ORIGENES(NOMBRE)
		VALUES (@NOMBREO);
   	SELECT @ID_ORIGEN=ID_ORIGEN 
		FROM CAT_ORIGENES 
			WHERE NOMBRE=@NOMBREO
END

INSERT INTO CAT_REMITENTES(ID_ORIGEN,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,CARGO,CORREO,TELEFONO)
	VALUES(@ID_ORIGEN,@NOMBRE,@APELLIDOP,@APELLIDOM,@CARGO,@CORRE0,@TELEFONO);


END
GO


--PRUEBA DE EJECUCION
EXEC sp_InsertRemitentesOrigen   'ALEJANDRO', 'GARCIA', 'ALVAREZ', 'JEFE DE SISTEMAS', 'ISC_GARCIA@OUTLOOK.COM','3131128425','H.AYUNTAMIENTO DE VILLA DE ALVAREZ'


