USE CORRESPONDENCIA
GO
CREATE VIEW VistaDetallada AS
	Select D.TURNADO AS "Enviado",D.FECHA_CAPTURA AS "Fecha de captura", D.COPIA_FISICA AS "Existe fisicamente", D.ESTADO As "Recibido",
		CU.NOMBRE+' '+CU.APELLIDO_PATERNO AS "Nombre Destino", CU.CORREO AS "Correo destino", CU.TELEFONO AS "Telefono destino",CD.NOMBRE AS "Direccion destino", CR.NOMBRE+' '+CR.APELLIDO_PATERNO AS "Nombre remitente",
		CR.CORREO AS "Correo remitente", CR.TELEFONO AS "Telefono remitente",CR.CARGO AS "Cargo",CO.NOMBRE AS "Direccion origen",CT.TIPO As "Tipo Documento",D.FECHA_ENVIO,
		D.FOLIO, D.RESUMEN,D.IMAGEN, D.RESPUESTA
			FROM ((((((TBL_DOCUMENTOS AS D 
				JOIN CAT_USUARIO AS CU 
					ON D.ID_DESTINATARIO=CU.ID_USUARIO)
				JOIN CAT_DIRECCION AS CD
					ON CD.ID_DIRECCION=CU.ID_DIRECCION)
				JOIN CAT_REMITENTES AS  CR
					ON CR.ID_REMITENTE=D.ID_REMITENTE)
				JOIN CAT_ORIGENES AS CO
					ON CO.ID_ORIGEN = CR.ID_ORIGEN)
				JOIN CAT_TIPO AS CT 
					ON CT.ID_TIPO=D.ID_TIPO_DOC)
					);