/***Vista Para agregar un nuevo remitente que no se encuentre en la listas predeterminadas***/
USE CORRESPONDENCIA
GO
CREATE VIEW VistaAddRemitente AS
	SELECT CR.NOMBRE,CR.APELLIDO_PATERNO,CR.APELLIDO_MATERNO,CR.CARGO,CO.NOMBRE 'NOMBRE ORIGEN',CR.CORREO,CR.TELEFONO
		FROM CAT_REMITENTES AS CR
			JOIN CAT_ORIGENES AS CO
				ON CO.ID_ORIGEN=CR.ID_ORIGEN



